// app/chat/[roomId]/_styles/chatStyles.ts
export const styles = {
  page: {
    minHeight: "100vh",
    padding: "24px",
    display: "flex",
    justifyContent: "center",
    alignItems: "stretch",
    background:
      "radial-gradient(circle at top, #1e293b 0, #020617 50%, #000000 100%)",
  },
  shell: {
    width: "100%",
    maxWidth: "980px",
    borderRadius: "24px",
    background: "rgba(15, 23, 42, 0.96)",
    boxShadow:
      "0 24px 60px rgba(15, 23, 42, 0.85), 0 0 0 1px rgba(148, 163, 184, 0.35)",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    backdropFilter: "blur(18px)",
  },
  header: {
    padding: "16px 20px",
    borderBottom: "1px solid rgba(51, 65, 85, 0.9)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    position: "relative" as const,
    overflow: "hidden",
  },
  headerTitle: {
    fontSize: "13px",
    letterSpacing: "0.2em",
    textTransform: "uppercase" as const,
    color: "#94a3b8",
  },
  headerRoom: {
    fontSize: "17px",
    fontWeight: 600,
    color: "#e2e8f0",
    marginTop: "4px",
  },
  headerPill: {
    fontSize: "11px",
    padding: "4px 10px",
    borderRadius: "999px",
    background: "rgba(15, 118, 110, 0.18)",
    border: "1px solid rgba(34, 197, 194, 0.2)",
    color: "#a5f3fc",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },
  headerGlow: {
    position: "absolute" as const,
    inset: "-40%",
    opacity: 0.16,
    background:
      "radial-gradient(circle at 0 0, rgba(56, 189, 248, 0.6), transparent 55%)",
    pointerEvents: "none" as const,
  },
  body: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    padding: "14px 14px 10px",
    gap: "10px",
  },
  messagesSurface: {
    flex: 1,
    borderRadius: "18px",
    border: "1px solid rgba(30, 64, 175, 0.4)",
    background:
      "radial-gradient(circle at top, rgba(15, 23, 42, 0.9), rgba(2, 6, 23, 0.95))",
    padding: "12px 12px 16px",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  messagesScroller: {
    flex: 1,
    overflowY: "auto" as const,
    paddingRight: "4px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
  },
  footer: {
    marginTop: "8px",
    padding: "10px 14px 14px",
    borderTop: "1px solid rgba(30, 64, 175, 0.55)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "6px",
  },
  footerRow: {
    display: "flex",
    alignItems: "flex-end",
    gap: "8px",
  },
  footerHint: {
    fontSize: "11px",
    color: "#64748b",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },

  // --- Typing indicator ---
  typingWrap: {
    display: "inline-flex",
    alignItems: "center",
    gap: "10px",
    padding: "6px 10px",
    borderRadius: "999px",
    background: "rgba(15, 23, 42, 0.95)",
    border: "1px solid rgba(148, 163, 184, 0.6)",
    boxShadow: "0 0 0 1px rgba(15, 23, 42, 1)",
    maxWidth: "100%",
  },
  dots: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  },
  dot: {
    width: "6px",
    height: "6px",
    borderRadius: "999px",
    background: "#cbd5f5",
    animation: "typingDot 900ms ease-in-out infinite",
  },
  typingText: {
    fontSize: "12px",
    color: "#e2e8f0",
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
} as const;
